[package]
name = "sss"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.86"
openraft = "0.9.17"
prost = "0.13.5"
sled = "0.34.7"
tokio = { version = "1.43.0", features = ["full"] }
tonic = "0.12.3"
serde = "1.0.217"
anyhow = "1.0.95"
